services:
  nginx_server:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: valerii_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped