services:
  aton:
    build:
      context: . 
      dockerfile: Dockerfile
    image: ghcr.io/derad6709/aton:main
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped